### ISSUE TITLE
Indexer Request: T411

### ISSUE THREAD

**Issue by ClubZERO1** [cardigann/cardigann#226] opened 2016-11-19 15:23 UTC
T411

Private. No invite required - open registration

https://www.t411.li/

French

**Comment by JigSawFr** [comment] 2016-11-20 18:45
Duplicate of https://github.com/cardigann/cardigann/issues/226

**Comment by kaso17** [comment] 2016-11-23 07:23
closing via #234

**Closed by kaso17** 2016-11-23 07:23 UTC
Labels: tracker
