### ISSUE TITLE
Wrong config folder  path

### ISSUE THREAD

**Issue by mmarquezs** [cardigann/cardigann#47] opened 2016-10-01 06:14 UTC
For some reason cardigann in my Arch Linux created the config folder in /.config/cardigann  instead of $HOME/.config/cardigann or /etc/xdg/cardigan/. (root user home is in /root ).

**Comment by lxt2** [comment] 2016-10-01 09:40
Interesting, are you running cardigann as root?

**Comment by mmarquezs** [comment] 2016-10-01 09:52
yes. I did set it as a service of systemd with your command and the process is running as root. Well if it wasn't running as root it couldn't have made the /.config folder.

**Comment by lxt2** [comment] 2016-10-01 11:39
Very true. I'll investigate. In the meantime, you can set CONFIG_DIR as an env to set it to the correct path, or just move the files to any of the valid search locations and it will use that. Thanks for the report.

**Comment by lxt2** [comment] 2016-10-02 12:01
This is the code that calculates paths: https://github.com/cardigann/xdg-go/blob/master/xdg_linux.go

Did you install the service using `cardigann service install`? Or did you create a custom systemd unit?

**Comment by mmarquezs** [comment] 2016-10-02 12:16
Using 'cardigann service install'

**Comment by aroundmyroom** [comment] 2016-10-02 19:47
starting the debian package after installing like dpkg -i cardigann.... 

when started as server

INFO[0000] Cardigann 1.8.0
DEBU[0000] Config path is /root/.config/cardigann/config.json
DEBU[0000] Cache dir is /root/.cache/cardigann
DEBU[0000] Definition load path is /usr/local/bin/definitions
DEBU[0000] Definition load path is /root/.config/cardigann/definitions
DEBU[0000] Definition load path is /etc/xdg/cardigann/definitions
INFO[0000] Listening on 0.0.0.0:5060

but started as service .. still a no go . . config and definitions not taken

and indeed I can confirm following

started as ./cardigann service start the config file is in /
started as cardigann service start the config file is in ./config/

**Comment by lxt2** [comment] 2016-10-02 23:00
Investigating.

**Comment by lxt2** [comment] 2016-10-03 01:26
I just pushed up some minor changes to the service stuff, available on edge (1.8.0-7-g65b2977).

Could I trouble you guys to run the service interactively with `./cardigann service --debug run` and post the output here?

**Comment by lxt2** [comment] 2016-10-03 01:35
Nope, I take it back. No definitions.

**Comment by lxt2** [comment] 2016-10-03 01:38
I had an old service running, the new one gets definitions, but the wrong config path.

**Comment by aroundmyroom** [comment] 2016-10-03 05:44
how to test new fixes when pulled? cause I need a deb package or a linux compiled binary .. 
it's not always available 

https://dl.equinox.io/cardigann/cardigann/stable

is now what I use .. or any other compiled binary. (unfortunately I cannot compile a go packet myself .. (it seems)) ;-)

**Comment by aroundmyroom** [comment] 2016-10-03 05:46
with 1.8.0
root@media:/usr/local/bin# ./cardigann service --debug run
I: 07:45:23 Running interactively
I: 07:45:23 Running service via linux-systemd.
I: 07:45:23 Cardigann 1.8.0 {}
I: 07:45:23 Listening on 0.0.0.0:5060 {}

no real info available yet

**Comment by mmarquezs** [comment] 2016-10-03 06:59
I'm not a very expert in systemd but it seems adding the user that will run the service to the unit it makes it work. I think if you don't add it the service uses the default user , which is actually root, but it seems the $HOME variable it's not set or something. But adding this under [Service] makes it work right:

`User=root`

**Comment by lxt2** [comment] 2016-10-03 08:36
@aroundmyroom https://dl.equinox.io/cardigann/cardigann/edge, or you can use `cardigann update --channel=edge` and it will update the binary in place. 

@mmarquezs yup, makes sense, I can fix that.

**Comment by lxt2** [comment] 2016-10-03 08:38
That said, this daemon should really not be running as root.

**Comment by mmarquezs** [comment] 2016-10-03 08:43
Yeah probably would be better to be it's own user. Like "cardigann"

**Comment by aroundmyroom** [comment] 2016-10-03 12:13
using cardigann update --channel=edge brings me back to 1.8.0 / keeps me on same version
when downloading from the URL and replace it manually it brings me to
INFO[0000] Cardigann 1.8.0-9-ga1b487c

using the 1st command again it's downgraded again ;-)

when I add User=Root in /etc/systemd/system/Cardigann.service it still wants to read the .config out of /.config not /root/.config/

**Comment by aroundmyroom** [comment] 2016-10-03 12:17
why not use something like this

[Service]
ExecStart=/usr/bin/cardigann --config /%i/.config/config.json
User=%i

**Comment by aroundmyroom** [comment] 2016-10-03 12:22
seems to fix my .config issue with some other commands

systemctl enable /etc/systemd/system/Cardigann.service
systemctl start Cardigann.service
systemctl status Cardigann.service

**Comment by lxt2** [comment] 2016-10-06 11:29
That's because HOME still isn't set. Frankly, just set CONFIG_DIR to whatever you want.

**Comment by lxt2** [comment] 2016-10-06 11:34
Ugh. @aroundmyroom https://github.com/cardigann/cardigann/issues/80

**Comment by aroundmyroom** [comment] 2016-10-06 16:12
;-)

**Comment by aroundmyroom** [comment] 2016-10-06 16:15
for me this thread is closed as the service is now working under the correct config path (for me)

**Closed** 2016-10-07 11:05 UTC
Labels: bug
