### ISSUE TITLE
How to install properly on ARM Rpi2

### ISSUE THREAD

**Issue by raspdealer** [cardigann/cardigann#98] opened 2016-10-10 17:44 UTC
Hi there,  

I've downloaded the last package and launched it in my console (./cardigann server instead of cardigann server in the doc)
I've added cinemaz in the graphic interface but it doesnt work...

If I check the config file, no user name or pass are stored foe the indexer. How should I do?

Thanks!

**Comment by lxt2** [comment] 2016-10-10 19:56
When you say no user name or pass are stored, is an entry added to your config.json? I just tested this with the latest release and it works, I assume you are using the latest stable? 

Could you start the server with `./cardigann server --debug` and see if there are any more clues?

**Comment by raspdealer** [comment] 2016-10-11 19:41
Last version. Entry exists but without credentials.
Should I install all the indexers?

**Comment by Markus92** [comment] 2016-10-11 21:28
Problem is reproducible here (fresh Raspbian Jessie Lite). Entry exists on config.json but it does not store the cookie, in my case for BHD.

**Comment by lxt2** [comment] 2016-10-13 03:58
What browser are you guys using? Are there any javascript console errors?

**Comment by lxt2** [comment] 2016-10-13 04:42
I can't reproduce this on OSX or Linux, it must be an ARMv5/Raspbian specific issue. I'll try and get a virtualized Raspbian environment working.

**Comment by Markus92** [comment] 2016-10-13 09:36
Both Edge/Chrome/Firefox exhibit the issue. No javascript console errors. One peculiar thing: the label of the form is "formHorizontalundefined" instead of formHorizontalcookie or anything like that.

Message me and I can get you shell access to play around.

**Comment by lxt2** [comment] 2016-10-13 21:59
@Markus92 that would be great, wanna email me some details to rznqsp8ffyeprn2l -at- gmail.com?

**Comment by Markus92** [comment] 2016-10-14 08:57
@lxt2 mailed you. Good luck!

**Comment by lxt2** [comment] 2016-10-15 02:47
I found a bug that might be causing this. Fixed in https://github.com/cardigann/cardigann/commit/af8f28301d8292fae3977026e407f98f8c67e050. Will release it as part of 1.8.7 shortly.

**Comment by lxt2** [comment] 2016-10-16 21:57
Sounds like this is fixed!

**Closed by lxt2** 2016-10-16 21:57 UTC
Labels: awaiting response
